moved checks and parameters into the subfunctions, abstract the apt simulate. Move argument functions up.

diff --git a/sources/functions/apt b/sources/functions/apt
--- a/sources/functions/apt
+++ b/sources/functions/apt
@@ -5,6 +5,49 @@
 
 if [[ -z $log ]]; then log="/root/logs/swizzin.log"; fi
 
+# Checks arguments and exports variables to add functionality to rest of packages
+_process_apt_args() {
+    # idiomatic parameter and option handling in sh
+    _unset_apt_args
+    _apt_packages=()
+    while test $# -gt 0
+    do
+        case "$1" in
+            --interactive) export _apt_interactive=true
+                echo "Info: APT set to interactive" | tee -a $log
+                ;;
+            --ignore-errors) export _apt_ignore_errors=true
+                echo "Info: APT will ignore errors" | tee -a $log
+                ;;
+            --skip-checks) export _apt_skip_checks=true
+                echo "Info: APT will skip sanity checks" | tee -a $log
+                ;;
+            --skip-update) export _apt_skip_update=true
+                echo "Info: APT will skip update" | tee -a $log
+                ;;
+            -*) echo "Error: Invalid option: $1"
+                exit 1
+                ;;
+            *) _apt_packages+=("$1")
+                ;;
+        esac
+        shift
+    done
+
+    if [[ -z ${_apt_packages[1]} ]]; then
+        export _apt_packages
+    fi
+}
+
+# Overwrites all the variables we use in this script
+_unset_apt_args (){
+    export _apt_ignore_errors=""
+    export _apt_interactive=""
+    export _apt_ignore_errors=""
+    export _apt_skip_checks=""
+    export _apt_packages=()
+}
+
 #Returns the version of the candidate package to install
 get_candidate_version () {
     package=$1
@@ -24,105 +67,34 @@ _check_installed (){
 
 # Check if apt is locked
 _check_dpkg_lock (){
-    # dpkg -i /dev/zero >> $log 2>&1
-    if lsof /var/lib/dpkg/lock >> $log 2>&1; then
-        echo "Error: dpkg database is locked. Please try again later" | tee -a $log
-        if [[ $_apt_ignore_errors != "true" ]]; then 
-            exit 1
+    if [[ $_apt_skip_checks != "true" ]]; then 
+        # dpkg -i /dev/zero >> $log 2>&1
+        if lsof /var/lib/dpkg/lock >> $log 2>&1; then
+            echo "Error: dpkg database is locked. Please try again later" | tee -a $log
+            if [[ $_apt_ignore_errors != "true" ]]; then 
+                exit 1
+            fi
         fi
     fi
-}
-
-# Checks arguments and exports variables to add functionality to rest of packages
-_process_apt_args() {
-# idiomatic parameter and option handling in sh
-_apt_packages=()
-_unset_apt_args
-while test $# -gt 0
-do
-    case "$1" in
-        --interactive) export _apt_interactive=true
-            echo "APT set to interactive" | tee -a $log
-            ;;
-        --ignore-errors) export _apt_ignore_errors=true
-            echo "APT will ignore errors" | tee -a $log
-            ;;
-        --skip-checks) export _apt_skip_checks=true
-            echo "APT will skip sanity checks" | tee -a $log
-            ;;
-        --skip-update) export _apt_skip_update=true
-            echo "APT will skip update" | tee -a $log
-            ;;
-        --*) echo "bad option $1"
-            exit 1
-            ;;
-        *) _apt_packages+=("$1")
-            ;;
-    esac
-    shift
-done
-
-if [[ -z $_apt_packages ]]; then
-    export _apt_packages
-fi
-}
-
-_unset_apt_args (){
-    export _apt_ignore_errors=""
-    export _apt_interactive=""
-    export _apt_ignore_errors=""
-    export _apt_skip_checks=""
-    export _apt_packages=()
 }
 
 # Check if install can run or not
 _apt_check (){
-    if ! apt-get check >> $log 2>&1; then
-        tail -10 $log | grep 'E:\|W:'
-        echo "Error: \`apt-get check\` failed, you may have broken packages. Aborting installation" | tee -a $log
-        if [[ $_apt_ignore_errors != "true" ]]; then 
-            exit 1
+    if [[ $_apt_skip_checks != "true" ]]; then 
+        if ! apt-get check >> $log 2>&1; then
+            tail -10 $log | grep 'E:\|W:'
+            echo "Error: \`apt-get check\` failed, you may have broken packages. Aborting installation" | tee -a $log
+            if [[ $_apt_ignore_errors != "true" ]]; then 
+                exit 1
+            fi
         fi
     fi
 }
 
-# Performing apt update and checking if it succeeded
-# shellcheck disable=SC2120
-apt_update () {
-    if [[ -n $1 ]]; then 
-        _process_apt_args "$@"
-    fi
-    echo "Performing apt update" | tee -a $log
-    if apt-get update >> $log 2>&1
-    then
-        return 0
-        # TODO check for Warnings and Errors in the output, as those will still return 0
-    else
-        tail -10 $log | grep 'E:\|W:'
-        echo "Error: \`apt-get update\` failed. Please consult the log." | tee -a $log
-        if [[ $_apt_ignore_errors != "true" ]]; then 
-            exit 1
-        fi
-    fi
-}
-export -f apt_update
-
-# Performs an upgrade and checks if it succeeded
-apt_upgrade() {
-    _process_apt_args "$@"
-    if [[ $_apt_skip_checks != "true" ]]; then 
-        _check_dpkg_lock
-        _apt_check
-    fi
-    
-    if [[ $_apt_skip_update != "true" ]]; then 
-        apt_update
-    fi
-
-    if [[ $_apt_skip_checks != "true" ]]; then 
-
-        # Check if the simulation would be fine 
-        if apt-get --simulate upgrade >> $log 2>&1; then
+# Performs a simulation of an apt-get call
+_apt_simulate(){
+if [[ $_apt_skip_checks != "true" ]]; then 
+        if apt-get --simulate "$@" >> $log 2>&1; then
             # echo "we're good"
             :
         else
@@ -133,6 +105,39 @@ apt_upgrade() {
             fi
         fi
     fi
+}
+
+# Performing apt update and checking if it succeeded
+# shellcheck disable=SC2120
+apt_update () {
+    if [[ -n $1 ]]; then 
+        _process_apt_args "$@"
+    fi
+    if [[ $_apt_skip_update != "true" ]]; then 
+        echo "Performing apt update" | tee -a $log
+        if apt-get update >> $log 2>&1
+        then
+            return 0
+            # TODO check for Warnings and Errors in the output, as those will still return 0
+        else
+            tail -10 $log | grep 'E:\|W:'
+            echo "Error: \`apt-get update\` failed. Please consult the log." | tee -a $log
+            if [[ $_apt_ignore_errors != "true" ]]; then 
+                exit 1
+            fi
+        fi
+    fi
+    _unset_apt_args
+}
+export -f apt_update
+
+# Performs an upgrade and checks if it succeeded
+apt_upgrade() {
+    _process_apt_args "$@"
+        _check_dpkg_lock
+        _apt_check
+        apt_update
+        _apt_simulate upgrade
 
     echo "Performing apt upgrade" | tee -a $log
 
@@ -149,32 +154,19 @@ apt_upgrade() {
             exit 1
         fi
     fi
+    _unset_apt_args
 }
 export -f apt_upgrade
 
 #Takes a space separated list of packages to install in a non-interactive manner
 apt_install (){
     _process_apt_args "$@"
-    if [[ $_apt_skip_checks != "true" ]]; then 
-        _check_dpkg_lock
-        _apt_check
-    fi
-    if [[ $_apt_skip_update != "true" ]]; then 
-        apt_update
-    fi
+    _check_dpkg_lock
+    _apt_check
 
-    # TODO figure out how to properly do this
-    # Check if the simulation would be fine 
-    if apt-get --simulate install "${_apt_packages[@]}" >> $log 2>&1; then
-        # echo "we're good"
-        :
-    else
-        tail -10 $log | grep 'E:'
-        echo "Error: The simulation check resulted in an error. Please consult the log. Aborting install" | tee -a $log
-        if [[ $_apt_ignore_errors != "true" ]]; then 
-            exit 1
-        fi
-    fi
+    apt_update
+    
+    _apt_simulate install "${_apt_packages[@]}"
 
     # Run the install
     echo "Performing installation of apt packages (${_apt_packages[*]})" | tee -a $log
@@ -193,6 +185,7 @@ apt_install (){
     fi
 
     # TODO check if any configs have changed and alert the users
+    _unset_apt_args
 }
 export -f apt_install
 
