Add check to prevent Deluge 1.3 from coexisting with qBit 4.3 as they are completely incompatible

diff --git a/sources/functions/libtorrent b/sources/functions/libtorrent
--- a/sources/functions/libtorrent
+++ b/sources/functions/libtorrent
@@ -59,6 +59,56 @@ function whiptail_libtorrent_rasterbar () {
   fi
 }
 
+function whiptail_libtorrent_install_resolve_conflict() {
+    message="Deluge 1.3 is not compatible with versions of qBittorrent greater than 4.3.0. You will be presented with options to resolve this conflict."
+    whiptail --msgbox "${message}" --title "ERROR: libtorrent conflict" --scrolltext 12 78
+    function=$(whiptail --title "ERROR: libtorrent conflict" --menu "Choose a resolution:" --ok-button "Continue" --nocancel 12 50 4 \
+        "Upgrade Deluge" "" \
+        "Downgrade qBittorrent" "" \
+        "Remove Deluge" "" \
+        "Remove qBittorrent" "" 3>&1 1>&2 2>&3)
+    case $function in
+        "Upgrade Deluge" ) export deluge=master;;
+        "Downgrade qBittorrent" ) export qbittorrent=4.2.5;;
+        "Remove Deluge" ) unset deluge; sed -i '/deluge/d' /root/results{,2};;
+        "Remove qBittorrent" ) unset qbittorrent; sed -i '/qbittorrent/d' /root/results{,2};;
+    esac
+}
+
+function check_client_compatibility() {
+    if [[ -f /install/.qbittorrent.lock ]] && [[ -z $qbittorrent ]]; then
+        qbittorrent=$(qbittorrent-nox --version | grep -oP '\d+\.\d+\.\d+')
+    fi
+    if [[ -f /install/.deluge.lock ]] && [[ -z $deluge ]]; then
+        dver=$(deluged -v | grep deluged | grep -oP '\d+\.\d+\.\d+')
+        case $dver in
+            1.3.*)
+                deluge=1.3-stable
+            ;;
+            *)
+                deluge=master
+            ;;
+        esac
+    fi
+    if [[ -n $deluge && -n $qbittorrent ]]; then
+        if [[ $deluge == "1.3-stable" ]]  || ( [[ $deluge == "repo" && $(lsb_release -cs) =~ ("stretch"|"buster"|"xenial"|"bionic") ]]); then
+            if dpkg --compare-versions ${qbittorrent} ge 4.3.0; then
+                if [[ -f /tmp/.install.lock ]]; then
+                    whiptail_libtorrent_install_resolve_conflict
+                else
+                    echo "ERROR: Deluge 1.3 is not compatible with versions of qBittorrent greater than 4.3.0."
+                    echo "You can resolve this error with one of the following actions:"
+                    echo " - Upgrade Deluge to at least v2"
+                    echo " - Downgrade qBittorrent to at most v4.2.5"
+                    echo " - Remove qBittorrent"
+                    echo " - Remove Deluge"
+                    exit 1
+                fi
+            fi
+        fi
+    fi
+}
+
 function skip_libtorrent_rasterbar () {
     if [[ ! -f /install/.libtorrent.lock ]]; then
         false; return
