Add qbittorrent package

diff --git a/sources/functions/utils b/sources/functions/utils
--- a/sources/functions/utils
+++ b/sources/functions/utils
@@ -67,3 +67,35 @@ function rm_if_exists () {
     fi
 }
 
+function port() {
+    LOW_BOUND=$1
+    UPPER_BOUND=$2
+    comm -23 <(seq ${LOW_BOUND} ${UPPER_BOUND} | sort) <(ss -Htan | awk '{print $4}' | cut -d':' -f2 | sort -u) | shuf | head -n 1
+}
+
+
+function check_ram() {
+    if [[ -z $1 ]]; then echo "Must specify a value to compare"; return 1; fi
+    apt-install -y -q bc > /dev/null 2>&1
+    ramtotal=$(cat /proc/meminfo | grep MemTotal | awk '{print $2}')
+    swaptotal=$(cat /proc/meminfo | grep SwapTotal | awk '{print $2}')
+    total=$(echo "$swaptotal + $ramtotal" | bc -l | numfmt --from-unit=1024)
+    needs=$(echo $1 | numfmt --from=iec)
+    if [[ $needs -gt $total ]]; then
+        false
+    else
+        true
+    fi
+}
+
+function tmp_swap_on() {
+    echo "Setup is enabling the use of a temporary 2GB swap file"
+    dd if=/dev/zero of=/.swapfile bs=1M count=2048 || { echo "ERROR: Cannot continue with install because swap file could not be created. Does device have 2GB of free space?"; exit 1; }
+    mkswap /.swapfile
+    swapon /.swapfile
+}
+
+function tmp_swap_off() {
+    swapoff /.swapfile
+    rm -f /.swapfile
+}
