Check for grsec and ask to remove and add rmgrsec function to box

diff --git a/scripts/box b/scripts/box
--- a/scripts/box
+++ b/scripts/box
@@ -354,6 +354,39 @@ function _panel () {
   /usr/local/bin/swizzin/panel/fix-disk $3
 }
 
+function _nukeovh() {
+  grsec=$(uname -a | grep -i grs)
+  if [[ -n $grsec ]]; then
+    echo
+    echo -e "Your server is currently running with kernel version: $(uname -r)"
+    echo -e "While not it is not required to switch, kernels with grsec are not recommend due to conflicts in the panel and other packages."
+    echo
+    echo -ne "Would you like swizzin to install the distribution kernel? (Default: Y) "; read input
+      case $input in
+        [yY] | [yY][Ee][Ss] | "" ) kernel=yes; echo "Your distribution's default kernel will be installed. You will need to reboot after these changes."  ;;
+        [nN] | [nN][Oo] ) echo "Why did you even run this function?" exit 1 ;;
+      *) kernel=yes; echo "Your distribution's default kernel will be installed. You will need to reboot after these changes."  ;;
+      esac
+      if [[ $kernel == yes ]]; then
+        if [[ $DISTRO == Ubuntu ]]; then
+          apt-get install -q -y linux-image-generic >>"${OUTTO}" 2>&1
+        elif [[ $DISTRO == Debian ]]; then
+          arch=$(uname -m)
+          if [[ $arch =~ ("i686"|"i386") ]]; then
+            apt-get install -q -y linux-image-686 >>"${OUTTO}" 2>&1
+          elif [[ $arch == x86_64 ]]; then
+            apt-get install -q -y linux-image-amd64 >>"${OUTTO}" 2>&1
+          fi
+        fi
+        mv /etc/grub.d/06_OVHkernel /etc/grub.d/25_OVHkernel
+        update-grub >>"${OUTTO}" 2>&1
+      fi
+    else
+    echo
+    echo -e "grsec not detected. Nothing to do."
+  fi
+}
+
 normal=$(tput sgr0)
 yellow=$(tput setaf 3)
 bold=$(tput bold)
@@ -414,6 +447,10 @@ case "$1" in
       exit 1
     fi
     _panel "$@"
+    exit 0
+  ;;
+  "rmgrsec")
+    _nukeovh
     exit 0
   ;;
   "update")
